### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by chan8616** [chan8616/TensorflowGUI#1]
가이드대로 파라미터를 입력해도 run버튼을 누르면 프로그램이 꺼집니다.

**Comment by YoNyeoSeok** [comment]
@chan8616 Window 환경에서 실행한 건지 여쭙니다.

**Comment by YoNyeoSeok** [comment]
@chan8616 <- 호출 기능으로 하면 바로 알림이 가는 것 같은데, 한번 확인해봐야 할 것 같습니다.

**Comment by YoNyeoSeok** [comment]
@chan8616 window 에서 비정상 종료되는 에러 해결하였습니다. 새로 git clone 해서 체크해보시면 됩니다.
