### ISSUE TITLE
fit_generator error

### ISSUE THREAD

**Issue by chan8616** [chan8616/TensorflowGUI#2]
**Describe the current behavior**  
clicked the run button after filling in the blank with parameters as given in the guide

**error message**
ValueError: `validation_steps=None` is only valid for a generator based on the `keras.utils.Sequence` class. Please specify `validation_steps` or use the `keras.utils.Sequence` class

-> I set the validation_steps with an arbitrary value and tried again, and got a new error message

ValueError: invalid literal for int() with base 10: '"10"'
  File "argparse.py", line 2307, in _get_value
    raise ArgumentError(action, msg % args)
argparse.ArgumentError: argument epochs: invalid int value: '"10"'

**Comment by YoNyeoSeok** [comment]
@chan8616 Revised. Check the new commit.
