### ISSUE TITLE
ImportError: cannot import name 'coco'

### ISSUE THREAD

**Issue by chan8616** [chan8616/TensorflowGUI#3]
Cannot start the program because there's no coco file under 'dataset'  folder.

**Error Message** 
File "app.py", line 10, in <module>
    from generator import IMAGE_CLASSIFICATION_TREE, COCO_TREE
  File "...TensorflowGUI\generator\__init__.py", line 12, in <module>
    from dataset import coco
ImportError: cannot import name 'coco'

**Comment by YoNyeoSeok** [comment]
Pass to #5
